_target_: nemo.collections.tts.data.audio_trimming.VadAudioTrimmer

model_name: "vad_multilingual_marblenet"
vad_sample_rate: 16000
vad_threshold: 0.4
device: "cpu"
frame_threshold: 3
frame_length: 4096
frame_step: 1024
pad_seconds: 0.2